version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_INITDB_ARGS="--encoding=UTF8 --locale=en_US.UTF8"
    mem_swappiness: -1 # temp workaround for synology
    
  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
    mem_swappiness: -1 # temp workaround for synology
